
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - standby.custom.com
  resources:
  - standbyservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - standby.custom.com
  resources:
  - standbyservices/finalizers
  verbs:
  - update
- apiGroups:
  - standby.custom.com
  resources:
  - standbyservices/status
  verbs:
  - get
  - patch
  - update
