# permissions for end users to edit standbyservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: standbyservice-editor-role
rules:
- apiGroups:
  - standby.custom.com
  resources:
  - standbyservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - standby.custom.com
  resources:
  - standbyservices/status
  verbs:
  - get
