apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: standby-service-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: StandbyService is the Schema for the standbyservices API
      displayName: Standby Service
      kind: StandbyService
      name: standbyservices.standby.custom.com
      version: v1alpha1
  description: This is the Standby Service Operator which can manually flip your services between active and standby deployments
  displayName: standby-service-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - service
  - standby
  links:
  - name: Standby Service Operator
    url: https://standby-service-operator.domain
  maturity: alpha
  provider:
    name: wschmidt
  version: 0.0.0
